# Trainer's parameters
# trainer:
#   epochs: 50
#   limit_train_batches: None
#   dev_mode: True
#   seed: 42
#   campaign_name: "camp0"
#   strategy: "diff_ar"
#   precision: 32
#   no_log: False
#   channels_last: False
#   profiler : None
#   val_interval: 1
#   load_model_ckpt: None

# Datamodule's parameters  change with hyperrparameteers
# data:
#   batch_size: 1
  # num_workers: 10
  # prefetch_factor: None
  # pin_memory: False

  # dataset: "smeagol"
  # num_input_steps: 2
  # num_pred_steps_train: 1
  # num_pred_steps_val_test: 5
  # num_inter_steps: 1
  # dataset_conf: None

# Model's parameters
# model:
#   model: "halfunet"
#   model_conf: None
#   run_name: "run"
#   lr: 1e-3
#   use_lr_scheduler: False
#   loss: "mse"


model:
  lr: 0.002

data: 
  batch_size: 1
  # num_workers: 10
  # prefetch_factor: None
  # pin_memory: False

  # dataset: "poesy"
  # num_input_steps: 2
  # num_pred_steps_train: 1
  # num_pred_steps_val_test: 5
  # num_inter_steps: 1
  # dataset_conf: None