data:
  #args forwarded (linked) to model
  dataset_name: "poesy"
  num_input_steps: 1
  num_pred_steps_train: 1
  num_pred_steps_val_test: 1
  batch_size: 1

  #other args
  num_workers: 4
  prefetch_factor: 2
  pin_memory: False 
  dataset_conf: config/datasets/poesy_refacto.json
  predict_conf: null